version: '3.7'

services: 
  ts-node-docker: 
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: ts-node-docker
    ports:
      - '3000:3000'
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=user
      - POSTGRES_DB=postgres
    volumes:
      - ./sql/data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/init.sql